[project]
name = "dataset-parallel-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch",
    "datasets",
    "openai",
    "python-dotenv",
    "tqdm",
    "sglang; sys_platform == 'linux'",
    "nvidia-cudnn-cu12==9.16.0.29; sys_platform == 'linux'",
    "flash-attn; sys_platform == 'linux'",
    "bitsandbytes; sys_platform == 'linux'",
    "jsonpath-ng",
    "aiohttp",
    "qdrant-client",
    "yasem",
    "hf_xet",
    "accelerate",
    "more-itertools",
    "semchunk",
    "fugashi",
    "unidic-lite",
    "onnxruntime-gpu",
    "polars",
    "tensorrt",
    "elasticsearch",
    "duckdb",
    "fastapi[standard]",
]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.uv]
override-dependencies = ["nvidia-cudnn-cu12==9.16.0.29", "xgrammar==0.1.31","torch"]

[tool.uv.sources]
sglang = { git = "https://github.com/sgl-project/sglang.git", subdirectory = "python", branch = "main" }
torch = { index = "pytorch-cu129" }

[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true

[tool.uv.extra-build-dependencies]
flash_attn = ["torch", "einops", "ninja", "setuptools"]

[tool.uv.extra-build-variables]
"flash_attn" = { TORCH_CUDA_ARCH_LIST = "9.0", MAX_JOBS = "64" }
"vllm" = { TORCH_CUDA_ARCH_LIST = "9.0", MAX_JOBS = "64" }
"tensorrt" = { NVIDIA_TENSORRT_DISABLE_INTERNAL_PIP = "0"}